original_questions = {
 'Children coming from the families of first generation leathers should be______': ['educated in regular schools','sent to special schools.','grouped together in c1as9 activities','made to repeat the class'],
 'When a student consistently forgets to do the homework, the student may': ['have a problem at home','be a naughty child','be a lazy student','not be liking the subject'],
 'Students of classes II and III appreciate teachers who___': ['behave with them.affectionately','dress up nicely','speak clearly','tell parents.to help them'],
 'Students can acquire values best through -': ['good role models.','teaching','obeying parents and teachers','reading religious books'],
 'Which of the following may be the LEAST APPROPRIATE activity  to start a day in school?': ['Assembly','Physical Training','Physical Training','Quiz'],
 'Which of the following statements is NOT correct?': ['A child with a .special need is always aware. of it','some children like strict teachers','Some children come to school without breakfast','Children copy the behavior of their parents'],
 'Chivangi. a student ofcl:ass IV usuallv takes awav things .belonging to hér classmates quietly. The teacher should —': ['to’ to understand tire reasons.','punish her.','complain .to the parents','ignore consiciering it as a child like behaviour.'],
 'Which pñneiple states that ‘Best learning takes place when the teacher is successful in arousing the interest of a student’?': ['Principle of Stimulation','Principle of Motivation','Principle of Association','Principle of goal setting'],
 'What is the aim of group activity in class room teaching?': ['To make most children participate in learning','To reduce the workload of the teacher','(3)	To clarify the concepts effectively','To provide freedom to students'],
 'According to the Right to Education Act, admission of children to a particular class has been proposed to be on the basis of—': ['age of the child','ability of the child','socio-economic status of the child','education of the parents'],
 'Seven year old Manohar is unable to read as per the class level. The teacher should —': ['give him reading exercises ofa lower level','inform the parents','detain him in the same class','try to find out the cause with expert help'],
 'Which of the statements given below is NOT TRUE for corporal punishment?': ['It makes children aggressive','It helps in disciplining pupils','It gives the message that ‘might is right’','It helps the emotional development of children'],
 'fhe story’ that the mountaineer 	was very exciting': ['narrated','explained','revealed','repeated'],
 'The snakes are so that they could swallow a man': ['huge','harm fu1','deadly','Inany'],
 'The cricket match scheduied for Saturday has been_____': ['called off','called out','caJJed oii','called up'],
 'It is a pleasure to drive on a smooth road but the road to the Tiger Hill was very ': ['coarse','dangerous','rough','steep'],
 'Please give me a 	of paprr. ': ['piece','peice','piese','peace'],
 'I can’t find my book.': ['gramer','grammes','gramar','grammar'],
 'The_______ of rich is poor':['apposite','opposite','t›positc','opposit'],
 'What	is	the	next number	in	of	the	number	sequence 1,2,3,5,8, 13,21,34,55,89, ... .....': ['144','127','103','90'],
 'The place value of zero in 1341.01 is-': ['Tenths','Units','Tens','Hundreds'],
 'Which	of	the	numbers	12,16,	18,	20	divides	completely	the number divisible by both 8 and 3?': ['12','16','18','20'],
 'A woman spends 6 months of her income in 8 millions.her annual income is Rs. 72300. what are her annual savings?': ['Rs. 18075','Rs. 21457.50','Rs.24100','Rs.12000'],
 'which digit  is at the thousands  place  in  2750.16': ['2','7','5','0'],
 'Which of the following numbers is divisible by 2,4, 6 and 8': ['543888','534800','542316','534810']
}