upper_questions = {
'Raju a student of your class is very tense due to the  acne on his face.What will you do?': ['Tell him that is normal and is due to hormonal changes', 'Ignore him', 'Tell him to go to a doctor as it is a medical problem', 'Scold  and tell him not to waste time on these issues'],
'If you come to know that a child of your class is facing problems related to parents separation at home, what would you do?':['Treat her/him sympathetically', 'Do not talk to the child on this issue', 'Talk to the parents', 'Be indifferent to the child'],
'For conducting a social science class in an interesting way, teachers should - ':['use role-plays effectively', 'give notes', 'give written homework', 'encourage extra reading'],
'A 11- 12  year old child generally  faces more problems related to —': ['need for peer approval', 'eye hand coordination', 'anxiety about studies', 'Understanding mathematics'],
'Which of the following may damage a low achieving student psychologically?':[' Discussing the  marks of individual students in the class', 'Making children maintain record of the class test marks', 'Discussing the correct answers in the class', 'Making children correct their own notebooks'],
'Which of the following statements about the role of a teacher is correct?':[ 'Teacher should have a friendly attitude towards students', 'Teacher should be a critic  only', 'Teacher should favour good students', 'Teacher should maintain a distance from students'],
'For ensuring and improving class discipline, the teacher should —':['arrange regular parent— teacher meetings','call authorities to the class', 'be strict with the students and punish them',' evaluate the methods and approaches used in the class'],
'Who has been meddling with my papers? I cant find my diary': ['interfering', 'working', 'resting',' leafing'],
'In the event of poisoning, immediately mike the person drink salt water to induce vomiting':['cause', 'control', 'clean', 'stop'],
' His benevolence has made it possible for many poor children to pursue education.':['charity', 'unselfishness', 'humanity', 'friendship'],
'He lost his way because he isGuided.':['mis','mal','un','dis'],
'When  I  was  a  child, my mother 	for wasting time in reading thecomics':['took me to task', 'lost ground', 'set her face against', 'put me in  mind'],
'You may do this the way you  like. Ithe whole affair':['keep of', 'wash my hands of', 'turn away from', 'stand my ground in'],
'In 1997, the population of China was approximately 1,240,000,000. How is this population written in scientific notation?':['1.24*109','1.24*108','1.24*107','1.24*106'],
'The side of right-angled triangle are in the ratio 5:12:13.The sum of the shortest side and the longest side is 144 cm, what is the length of the third side of the triangle?':['96cm', '104cm','40cm','6cm'],
'The  circumference of the front wheel and the rear wheel  of a tricycle are 60cm and 45cm respectively. When Bobby begins to ride the tricycle, the point P on the wheel and the point Q on the rear wheel touch the ground. What is minimum distance travelled before P and Q will touch the ground again at the same time?':['180cm','206cm','360cm','105cm'],
'The weight of a 3 month old baby is 6.08kg. This is 190% of her weight at birth. what was her weight at birth?':['3.2kg','3.02kg','2.3kg','2.03kg'],
' Which conclusion about the roots of the equation (x-1)2 = -1 is correct?':[' The roots are imaginary and unequal', 'The roots are imaginary and equal', 'The roots are real and equal', 'The roots are real and unequal'],
'What is the sum of internal angles of a polygon of 20 sides?':['3240','720','1620','360'],
' A star has a diameter of approximately 0.5 that of Earth and mass of 0.1 that of Earth. The force experienced by a  body of mass 1Kg on the surface of that star compared to that on Earth is greater by factor:':['0.4','0.2','0.8','1'],
'Which of the following quantities must be determined in order that the thermal capacity of a body can be calculated when specific heat capacity of the body is known?':['Mass', 'Latent Heat', 'Temperature', 'Thermal Conductivity'],
'A  diverging   lens   is  prescribed   by  ophthalmologistto correct-':[' myopia', 'presbyopia', 'hyper Metropia', 'astigmatism'],
'The relative atomic masses of man elements are not whole numbers because- ':[ 'elements are mixtures of isotopes', ' elements are mixtures of isobars', 'elements have fractional absolute masses', ' all elements are not in gaseous state'],
' A solution x reacts with crushed egg-shells to give a gas that turns lime water milky. The solution x contains:':['HCl(Aq)','NaCl(Aq)','LiCl(Aq)','KCl(Aq)'],
'Which of the following is a neutralization reaction?':['HCl+ NaOH →Nacl+H2O','Zn+H2SO4 →ZnSO4 +H2','2Cu+H2O+CO2 +O2→ Cu(OH)2+CuCO3','SO2+H2O→H2SO3']
}